os: linux
dist: jammy
language: java
jdk: openjdk17
before_install:
 - pip install -r requirements.txt
 - mvn spotless:check -B
 - black --fast --check .
 - git clone --depth=50 https://github.com/wala/IDE /tmp/IDE
 - git clone --depth=50 https://github.com/ponder-lab/jython3.git /tmp/jython3
install:
 - pushd /tmp/jython3
 - ant
 - pushd dist
 - mvn install:install-file -Dfile=./jython-dev.jar -DgroupId="org.python" -DartifactId="jython3" -Dversion="0.0.1-SNAPSHOT" -Dpackaging="jar" -DgeneratePom=true
 - popd
 - popd
 - pushd /tmp/IDE/com.ibm.wala.cast.lsp
 - mvn install -B -q -DskipTests
 - popd
script:
 - mvn -Dlogging.config.file=./logging.ci.properties verify -Pjacoco coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN -B
deploy:
  provider: script
  script: mvn -s .travis.settings.xml -Dgithub.username=$GITHUB_USERNAME -Dgithub.password=$GITHUB_TOKEN deploy -DskipTests
  skip_cleanup: true
  on:
    branch: master
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
notifications:
  slack:
    secure: MVF8H5hIhaBw4NiT16g8KmFJMGKb64H410Sdc/UDaRXnZBHxUV8Qg4Lf70V5usWRsttqJPWCM/XzDf3vjDhx9gKq9zj+D+KchUzEu3W0UTan80JxJ8HrzDbgl5/30KXstmeTQseB1nkkwInsP49AJQh4w0fsoTjkYXNfp07TUPYqs7WM9ygyz9g7AR4kSpqjQh9b1ZAOVMKdP6we86OrWU/R6Je//4TIXiG3la60XCqB0Ad283yB7K+0wuPKVlp0SMo0sq1Wq+Pfm64wJHDPSTzVFomN7nNRFngts5GlCzEqPkEzSnQUgSYTzx+oQpPJLln48UrM9876DEKCJYV8xA01jxb0mdBwW5MWclsb+NgM8Z4rX3+kUdUixxfYEFBcPHFcFNGPLIoaq6hjFqMKOrv1xUu0SEi2wzkb245Uvd6o4ZCYOWavKo8f9m2abxID+A6pOtvx7N+VYiYgs91+OV/2goQYP9D3lng6ZzKvqGoP3SoejyV2EJb/GSYXLc7YAQ4SJWhY8NZUCpD3B72zx6Y4gPixy7/KZ6i2pvJHDEVSeA04nvPs4vPXgWnXdY7wbjJu4pRg8l4jYhJtyIzUlnu8ShGU1j7EZhNj3H1LxnFgvjRBtU2GYNuzukse5oKrh53J8d7dQZXJnB8+wcnyiN/VPym9Mc47uBGz5SPqkMM=
