os: linux
dist: focal
language: java
jdk: openjdk11
before_install:
 - git clone --depth=500 https://github.com/wala/WALA /tmp/WALA
 - git clone --depth=50 https://github.com/ponder-lab/IDE /tmp/IDE
 - git clone https://github.com/juliandolby/jython3.git /tmp/jython3
install:
 - pushd /tmp/jython3
 - ant
 - pushd dist
 - mvn install:install-file -Dfile=./jython-dev.jar -DgroupId="org.python" -DartifactId="jython3" -Dversion="0.0.1-SNAPSHOT" -Dpackaging="jar" -DgeneratePom=true
 - popd
 - popd
 - pushd /tmp/WALA
 - git checkout v1.5.8
 - ./gradlew build -x test
 - ./gradlew publishToMavenLocal -x signRemotePublication
 - popd
 - pushd /tmp/IDE/com.ibm.wala.cast.lsp
 - mvn clean install -B -q -DskipTests
 - popd
script:
 - mvn clean install -B
sudo: false
cache:
  directories:
    - $HOME/.m2
